### ISSUE TITLE
Create multiple tunnel on the same machine

### ISSUE THREAD

**Issue by julien-blanchon** [amalshaji/portr#107]
Hello,

Look like I can't make more than a single tunnel on the same machine, because Portr try to launch a new Inspector (7777) for each tunnel and the port is already use.

To reproduce:

```shell
$ portr http 3000 --subdomain d1
🌍 Starting tunnel connection for :3000
🚨 Portr inspector running on http://localhost:7777
🎉 Tunnel connected: https://d1.PORTR_DOMAIN -> 🌐 -> localhost:3000
```

And then

```shell
$ portr http 3001 --subdomain d2
🌍 Starting tunnel connection for :5000
🚨 Portr inspector running on http://localhost:7777
```

**Comment by julien-blanchon** [comment]
Maybe add a condition here: https://github.com/amalshaji/portr/blob/f50753c4640f7a55abd1375e24cfb73e45d58d3c/tunnel/cmd/portr/start.go#L37-L38

**Comment by amalshaji** [comment]
@julien-blanchon For now, you can define the tunnels in the config (`portr config edit`) and then start tunnels using `portr start tunnel1 tunnel2`

https://portr.dev/client/templates/

**Comment by julien-blanchon** [comment]
Good to know thanks, I suppose this is not intended to be like this ? I keep this issue open as potential new features ?

**Comment by amalshaji** [comment]
This is fixed in https://github.com/amalshaji/portr/releases/tag/0.0.21-beta

**Comment by julien-blanchon** [comment]
Awesome thanks
