### ISSUE TITLE
failed to initialize database

### ISSUE THREAD

**Issue by CorrectRoadH** [amalshaji/portr#26]
**Describe the bug**
run portr in ubuntu throw error 
```
2024/04/04 14:57:56 /home/runner/work/portr/portr/tunnel/internal/client/db/db.go:19
[error] failed to initialize database, got error unable to open database file: out of memory (14)
2024/04/04 14:57:56 failed to connect database: unable to open database file: out of memory (14)
```
**To Reproduce**
1. wget https://github.com/amalshaji/portr/releases/download/0.0.10-beta/portr_0.0.10-beta_Linux_x86_64.zip
2. unzip portr_0.0.10-beta_Linux_x86_64.zip
3. ./portr http 8088

**Expected behavior**

**Screenshots**
![CleanShot 2024-04-04 at 14 59 52@2x](https://github.com/amalshaji/portr/assets/29306285/947e30f6-cb52-4310-9056-e44ad182d67e)

**Additional context**

**Comment by amalshaji** [comment]
Works fine on Mac, need to test on Linux

**Comment by amalshaji** [comment]
This is due to the missing `~/.portr` directory. If you do `./portr auth` first, the folder will be created, and this error won't be shown.
