### ISSUE TITLE
WSL2 Portr inspector not working

### ISSUE THREAD

**Issue by Mistic92** [amalshaji/portr#38]
**Describe the bug**
I have configured portr server on hetzner, did client auth and now trying to see inspector dashboard. When trying to open http://localhost:7777 I'm getting just ERR_CONNECTION_RESET. 

**To Reproduce**
1. Install portr client on wsl2 and try to open inspector dash. 

**Expected behavior**
Dashboard working

**Comment by amalshaji** [comment]
Have you tried running it on Windows?

**Comment by amalshaji** [comment]
@Mistic92 Any updates on this?
