### ISSUE TITLE
Invalid state

### ISSUE THREAD

**Issue by HarunKilic** [amalshaji/portr#53]
**Describe the bug**
After setup when I forward a port it gives an url, when going to the URL it asks for login, after login, it says "Invalid state'

**Comment by amalshaji** [comment]
Can you add a screenshot?

**Comment by HarunKilic** [comment]
Sure, its pretty empty tho:
![image](https://github.com/amalshaji/portr/assets/13366825/ef856427-0d91-4147-a081-717238908ab8)

**Comment by amalshaji** [comment]
Is this a screenshot of the browser? Can you add more info?

**Comment by HarunKilic** [comment]
Yes. 
I get error 400 from the admin app. 
`https://portr.example.com/api/v1/auth/github/callback?code=SOME_CODE&state=SOME_STATE`

It might be due to the infrastructure. 
I've forwarded the port 8000 through Nginx Proxy Manager. Which works fine. 
Port 2222 is forwarded using iptables to extern server with tailscale.

**Comment by amalshaji** [comment]
Must be, can you check if this cookie is being set correctly
https://github.com/amalshaji/portr/blob/23dbede7c7fc7d49d54467ec1d9df5da0e8c5c20/admin/src/portr_admin/apis/v1/auth.py#L55-L57

**Comment by HarunKilic** [comment]
Yea, there is two cookies: 
![image](https://github.com/amalshaji/portr/assets/13366825/8c4bec5f-7554-42d1-822d-33418acae016)

**Comment by amalshaji** [comment]
Can you check if the state in the callback and the cookie are the same? Ideally they should be
