### ISSUE TITLE
not starting

### ISSUE THREAD

**Issue by tails2012timnew** [amalshaji/portr#64]
**Describe the bug**
I tried to start the program with portr http 1615 and it said 'Post "https://localhost:8000/api/v1/connections/": dial tcp [::1]:8000: connectex: No connection could be made because the target machine actively refused it.'

**To Reproduce**
1. type portr http 1615

**Expected behavior**
my expected behavior is for it to start
**Screenshots**
![image](https://github.com/amalshaji/portr/assets/152324947/bba24383-6432-4e8d-87e7-6269150fd9ee)

**Additional context**
pls fix

**Comment by amalshaji** [comment]
You need start the servers first

**Comment by tails2012timnew** [comment]
so there isnt a server already made?

**Comment by amalshaji** [comment]
No
