### ISSUE TITLE
[Cloudflare] Subdomain is not created

### ISSUE THREAD

**Issue by Timmlion** [amalshaji/portr#65]
When running portr in HTTP mode, I get "Tunnel connected: https://test.example.com -> 🌐 -> localhost:1111," but I can't connect it to my local API. When I look into the DNS > Records tab in the Cloudflare panel, I don't see any new record created for the "test" subdomain.

**To Reproduce**
1. Run portr in Docker
2. Start client
3. No connection via defined subdomain

**Expected behavior**
When the client is run, the defined subdomain should be created in Cloudflare, and I could connect to my local resources.

**Additional context**
It's not working in HTTP mode, but it works in TCP mode, so I know that the connection itself is working.

**Comment by amalshaji** [comment]
Is the portr server running in your local?

**Comment by Timmlion** [comment]
The server is running on an Azure VM. I've opened ports 80, 443, 8000, 2222, and 30001-40001

**Comment by amalshaji** [comment]
Portr doesn't create subdomains on the fly. It uses a wildcard certificate for *.example.com. You need to add DNS A records for `@` and `*` pointing to your server address. This was missing in the docs, I've updated the same. https://portr.dev/server/#prerequisites

**Comment by Timmlion** [comment]
I was missing * record, it works now. Thanks :)
